{% set name = "tsod" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 101289a3798727ae41686b552be8d492581a026373e6a61e6872c16e7706e49c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - joblib
    - numba

test:
  imports:
    - tsod
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/DHI/tsod

  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Anomaly Detection for time series data
  doc_url: https://dhi.github.io/tsod/

extra:
  recipe-maintainers:
    - ecomodeller
